<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "additional_sysinfo"
 *
 * Auto generated by Extension Builder 2015-07-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Additional system information',
	'description' => 'Additional system information',
	'category' => 'plugin',
	'author' => 'Patrick Schriner',
	'author_email' => 'patrick.schriner@diemedialen.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.5.0-7.9.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);